- name: Install the Elasticsearch yum repository (Logstash included)
  yum_repository:
    name: elasitcsearch-7.X
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    description: Elasticsearch repository for 7.x packages
    state: present


- name: Install the Kibana yum repository
  yum_repository:
    name: kibana-7.X
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    description: Kibana repository for 7.x packages
    state: present


- name: Install the elk stack
  dnf:
    name:
      - elasticsearch
      - kibana
      - logstash
    state: present


- name: Configure elasticsearch
  template:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify: Restart elasticsearch


- name: Configure kibana
  template:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml
    owner: root
    group: kibana
    mode: 0644
  notify: Restart kibana


- name: Configure logstash
  template:
    src: logstash.yml
    dest: /etc/logstash/logstash.yml
    owner: root
    group: root
    mode: 0644
  notify: Restart logstash


- name: Configure logstash pipeline
  template:
    src: beats.conf
    dest: /etc/logstash/conf.d/beats.conf
    owner: root
    group: logstash
    mode: 0640


- name: Configure the firewall
  firewalld:
    port: '{{ item }}/tcp'
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - '{{ elk_server_elasticsearch_port }}'
    - '{{ elk_server_kibana_port }}'
